name: Filter IP Addresses for Country

on:
  schedule:
    - cron: '0 18 * * *' # 每天下午六点 UTC 运行，对应中国时间每天凌晨两点
  workflow_dispatch: # 手动触发

jobs:
  run-script:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Enable debug logging
      run: echo "ACTIONS_RUNNER_DEBUG=true" >> $GITHUB_ENV

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Cache Python dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        set -x  # 打开详细日志输出
        echo "Upgrading pip..."
        python -m pip install --upgrade pip 2>&1 | tee pip_upgrade.log
        echo "Installing requests library..."
        pip install requests 2>&1 | tee pip_install.log

    - name: Run script
      run: |
        set -x
        echo "Running the filtering script..."
        python filter_iplist_for_country.py 2>&1 | tee script_output.log

    - name: Check if changes are present
      id: check_changes
      run: |
        set -x
        echo "Checking for changes in the repository..."
        git status
        if git diff --quiet; then
          echo "No changes detected."
        else
          echo "changed=true" >> $GITHUB_ENV
        fi
      shell: bash

    - name: Commit and push changes
      if: env.changed == 'true'
      run: |
        set -x
        echo "Adding new files to staging area..."
        git add all_cn.txt all_cn_ipv6.txt delegated-apnic-latest
        echo "Configuring Git user information..."
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        echo "Committing changes..."
        git commit -m "Update IP lists"
        echo "Pushing changes to repository..."
        git push --force origin ${{ github.ref }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Log completion
      run: echo "Workflow completed successfully."
