name: Update all_cn.txt

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 1 * * *'

jobs:
  update-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Generate all_cn.txt
      run: |
        python -c "
import requests

url = 'https://ftp.apnic.net/stats/apnic/delegated-apnic-latest'
response = requests.get(url)
if response.status_code == 200:
    with open('all_cn.txt', 'w') as file:
        for line in response.text.splitlines():
            parts = line.split('|')
            if len(parts) > 5 and parts[1] == 'CN' and parts[2] == 'ipv4':
                ip_prefix = parts[3]
                num_ips = int(parts[4])
                cidr = 32 - (num_ips - 1).bit_length()
                cidr_block = f'{ip_prefix}/{cidr}'
                file.write(cidr_block + '\n')
else:
    print('Failed to download the IP list.')
"

    - name: Commit and push all_cn.txt
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

        # Check for changes in all_cn.txt and commit if there are any.
        if git diff --quiet all_cn.txt; then
          echo "No changes detected."
        else
          git add all_cn.txt
          git commit -m "Update all_cn.txt with CN IPv4 addresses" || echo "No changes to commit"
          git push origin HEAD
        fi
